"""Turn a Denial into a pull request against the repo that defines the role."""

from github import GitHubError
from terraform import NoSafeFix, find_role, fix_filename, render_fix, role_name_from_arn


class RoleNotFound(Exception):
    pass


def open_fix_pr(denial, gh, explainer=None):
    """Open (or find the existing) fix PR for this denial. Returns the PR URL.

    explainer(role, terraform_source) -> dict | None adds an AI review section.
    """
    base = gh.default_branch()
    base_sha = gh.branch_sha(base)

    role_name = role_name_from_arn(denial.principal_arn)
    files = gh.tf_files(base_sha)
    role = find_role(files, role_name)
    if role is None:
        raise RoleNotFound(f"no aws_iam_role with name = \"{role_name}\" in {gh.repo}")

    hcl = render_fix(denial, role)  # raises NoSafeFix for things we won't auto-fix
    path = _beside(role.path, fix_filename(denial))
    branch = f"whydenied/{denial.id}"

    try:
        gh.create_branch(branch, base_sha)
    except GitHubError as e:
        if e.status != 422:  # 422 = branch already exists, e.g. a retried invocation
            raise
        existing = gh.find_pull_request(branch)
        if existing:
            return existing

    try:
        gh.create_file(path, hcl, branch, f"Allow {denial.action} for {role_name}")
    except GitHubError as e:
        if e.status != 422:  # 422 = file already on the branch from an earlier attempt
            raise

    return gh.open_pull_request(
        title=f"WhyDenied: allow {denial.action} for {role_name}",
        head=branch,
        base=base,
        body=pr_body(denial, role, path, explainer(role, files[role.path]) if explainer else None),
    )


def pr_body(denial, role, path, ai=None):
    return f"""### What happened

`{denial.principal_arn}` was denied **`{denial.action}`** on

```
{denial.resource}
```

AWS said: *{_reason_text(denial)}*

First seen {denial.event_time} in `{denial.region}`.

### The fix

Adds `{path}`, an inline policy on `{role.address}` that allows **only** `{denial.action}` on **only** that resource. Nothing else about the role changes.

{_ai_section(ai)}### Before merging

- [ ] The role *should* be able to do this. If not, close this PR and fix the caller instead.
- [ ] Run `terraform plan` and check the only change is this one policy.

---
Opened automatically by [WhyDenied](https://github.com/tusharkhatriofficial/whydenied).
"""


def _ai_section(ai):
    if not ai:
        return ""
    expected = "yes" if ai["looks_expected"] else "**no, check this carefully**"
    return f"""### AI review

{ai['summary']}

- **Looks like normal use of this role:** {expected}
- **Risk if granted:** {ai['risk']}. {ai['risk_reason']}
- **Check before merging:** {ai['reviewer_tip']}

<sub>Written by an AI model from the error and the Terraform. The fix above was generated by code, not by the AI.</sub>

"""


def _reason_text(denial):
    message = denial.error_message
    return message[message.find("because"):] if "because" in message else denial.reason


def _beside(role_path, filename):
    """Put the fix in the same directory as the file that defines the role."""
    directory = role_path.rsplit("/", 1)[0] if "/" in role_path else ""
    return f"{directory}/{filename}" if directory else filename


__all__ = ["open_fix_pr", "pr_body", "RoleNotFound", "NoSafeFix"]
