"""Find an IAM role in Terraform code and write the policy that fixes a denial.

Pure functions only (no AWS or GitHub calls), so they're easy to test.
"""

import re
from dataclasses import dataclass

_ROLE_BLOCK_RE = re.compile(r'resource\s+"aws_iam_role"\s+"(?P<label>[\w-]+)"\s*\{')
_NAME_RE = re.compile(r'^\s*name\s*=\s*"(?P<name>[^"]+)"', re.MULTILINE)

_ANY_NAME_RE = re.compile(r'^\s*name\s*=\s*(?P<value>.*?)\s*$', re.MULTILINE)
_NAME_PREFIX_RE = re.compile(r'^\s*name_prefix\s*=', re.MULTILINE)
# A quoted string of IAM role name characters, optionally followed by a comment.
# "${...}" can't match: _top_level has already reduced it to "$".
_LITERAL_RE = re.compile(r'^"(?P<name>[\w+=,.@-]+)"\s*(?:(?:#|//).*)?$')

_FIX_HINT = "so WhyDenied can match denials to this role."
_ISSUES = {
    "name_prefix": f"Uses name_prefix. Set an explicit name {_FIX_HINT}",
    "expression": f"Name comes from a variable or expression. Set a literal name {_FIX_HINT}",
    "missing": f"Has no name, so Terraform generates a random one. Set an explicit name {_FIX_HINT}",
}


@dataclass
class RoleLocation:
    path: str      # file that defines the role, e.g. "main.tf"
    address: str   # Terraform address, e.g. "aws_iam_role.orders_api"


class NoSafeFix(Exception):
    """Raised when WhyDenied can't (or shouldn't) generate a fix automatically."""


def role_name_from_arn(arn):
    # arn:aws:iam::123456789012:role/some/path/orders-api-role -> orders-api-role
    return arn.split(":role/", 1)[-1].split("/")[-1]


def find_role(files, role_name):
    """Search {path: content} for the aws_iam_role whose name matches.

    Only explicit `name = "..."` is supported; roles named with name_prefix or
    a variable can't be matched from the ARN alone.
    """
    for path, content in sorted(files.items()):
        if not path.endswith(".tf"):
            continue
        for match in _ROLE_BLOCK_RE.finditer(content):
            body = _top_level(_block_body(content, match.end()))
            name = _NAME_RE.search(body)
            if name and name.group("name") == role_name:
                return RoleLocation(path=path, address=f"aws_iam_role.{match.group('label')}")
    return None


def list_roles(files):
    """Every aws_iam_role in {path: content}, and whether WhyDenied can match it by name.

    Returns dicts with address, name, path, ready and issue (None when ready).
    """
    roles = []
    for path, content in sorted(files.items()):
        if not path.endswith(".tf"):
            continue
        for match in _ROLE_BLOCK_RE.finditer(content):
            body = _top_level(_block_body(content, match.end()))
            name, issue = _role_name(body)
            roles.append({
                "address": f"aws_iam_role.{match.group('label')}",
                "name": name,
                "path": path,
                "ready": issue is None,
                "issue": issue,
            })
    return roles


def _role_name(body):
    """(name, None) for a literal name, otherwise (None, issue)."""
    found = _ANY_NAME_RE.search(body)
    if found:
        literal = _LITERAL_RE.match(found.group("value"))
        if literal:
            return literal.group("name"), None
        # var.x, local.x, "${...}", function calls and so on
        return None, _ISSUES["expression"]
    if _NAME_PREFIX_RE.search(body):
        return None, _ISSUES["name_prefix"]
    return None, _ISSUES["missing"]


def fix_filename(denial):
    return f"whydenied_{_slug(denial.action)}_{denial.id[:6]}.tf"


def render_fix(denial, role):
    """Return Terraform that grants exactly the denied action on the denied resource."""
    if denial.reason != "missing_identity_allow":
        raise NoSafeFix(
            f"reason is {denial.reason!r}; only a missing identity-policy Allow is fixed automatically"
        )
    if "*" in denial.action:
        raise NoSafeFix(f"refusing to grant a wildcard action: {denial.action}")

    label = f"whydenied_{_slug(denial.action)}_{denial.id[:6]}"
    return f'''# Generated by WhyDenied. Review before merging.
#
# {denial.principal_arn}
# was denied {denial.action}
# on {denial.resource}
# because no identity-based policy allowed it.
# First seen {denial.event_time}.

resource "aws_iam_role_policy" "{label}" {{
  name = "{label}"
  role = {role.address}.name

  policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [{{
      Effect   = "Allow"
      Action   = "{denial.action}"
      Resource = "{denial.resource}"
    }}]
  }})
}}
'''


def _slug(action):
    return re.sub(r"[^a-z0-9]+", "_", action.lower()).strip("_")


def _top_level(body):
    """Drop everything inside nested blocks, so `name` in inline_policy {} isn't matched."""
    out, depth = [], 0
    for ch in body:
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
        elif depth == 0:
            out.append(ch)
    return "".join(out)


def _block_body(content, start):
    """Text between the opening brace (just before `start`) and its matching close."""
    depth = 1
    i = start
    while i < len(content) and depth:
        if content[i] == "{":
            depth += 1
        elif content[i] == "}":
            depth -= 1
        i += 1
    return content[start:i - 1]
